### ISSUE TITLE
Translation in faculty - overview

### ISSUE THREAD

**Issue by jahbini** [nia-edu-kh/nia-web#14]
Dear Mr.Jim
        As for the event page, I can't seem to find the right words to describe it in khmer as well as the word overview in this page.
·       Welcome to Our College = សូមស្វាគមន៍មកកាន់វិទ្យាស្ថាន
·       9,301 students graduated from the National Institute of Agriculture since 1984. = ចាប់តាំងពីបើកដំណើរការឡើងវិញនៅឆ្នាំ១៩៨៤មក និស្សិតចំនួន៩.៣០១នាក់ បានបញ្ចប់ការសិក្សាពីវិទ្យាស្ថានជាតិកសិកម្មព្រែកលៀប។
·       They became agriculturists in important role of, for example, extension workers, trainers, traders, administrators, secretaries, supervisors, managers, directors, inspectors, researchers, scientists and other leaders. They work in the field of agriculture, rural development, environment, water resource and trade among others. = និស្សិតទាំងនោះបានក្លាយជាអ្នកជំនាញកសិកម្ម ដែលមានតួនាទីសំខាន់ដូចជា ភ្នាក់ងារផ្សព្វផ្សាយ គ្រូបង្គោល ពាណិជ្ជករ អ្នករដ្ឋបាល លេខាធិការ អ្នកគ្រប់គ្រង នាយកនាយិការ អ្នកស្រាវជ្រាវ អ្នកវិទ្យាសាស្ត្រ និងអ្នកដឹកនាំផ្សេងទៀត។ អ្នកជំនាញកសិកម្មទាំងនោះកំពុងបម្រើការឲ្យស្ថាប័នរដ្ឋស្ថាប័នក្រៅ រដ្ឋាភិបាល និងស្ថាប័នឯកជនក្នុងវិស័យកសិកម្ម អភិវឌ្ឍន៍ជនបទ បរិស្ថាន ធនធានទឹក និងពាណិជ្ជកម្មជាដើម។

Best regards,
Ouk Makaden

**Comment by KongSovanara** [comment]
Dear Mr.Jim,
As it is reviewed and revised from Makaden both English and Khmer as follows:
· Welcome to Our Institute =វិទ្យាស្ថានសូមស្វាគមន៍
· 9,301 students graduated from the National Institute of Agriculture since 1984. = មាននិស្សិតចំនួន៩.៣០១នាក់បានចប់ការសិក្សាពីវិទ្យាស្ថានជាតិកសិកម្មព្រែកលៀបចាប់តាំងពីការបើកដំណើរការឡើងវិញនៅឆ្នាំ១៩៨៤។
· They transformed into agriculturists in important roles of, for example, extension workers, trainers, traders, administrators, secretaries, supervisors, managers, directors, inspectors, researchers, scientists and other leaders. They​ are working in the field of agriculture, rural development, environment, water resource and trade both public and private among others. = និស្សិតទាំងនោះបានប្រែក្លាយជាអ្នកជំនាញការកសិកម្ម ដែលមានតួនាទីសំខាន់ដូចជា ភ្នាក់ងារផ្សព្វផ្សាយ គ្រូបង្គោល ពាណិជ្ជករ អ្នករដ្ឋបាល លេខាធិការ អ្នកគ្រប់គ្រងថ្នាក់ទាប អ្នកគ្រប់គ្រង នាយក នាយិកា អ្នកស្រាវជ្រាវ អ្នកវិទ្យាសាស្ត្រ និងអ្នកដឹកនាំផ្សេងៗទៀត។ អ្នកជំនាញកសិកម្មទាំងនោះកំពុងតែបម្រើការឪ្យស្ថាប័នរដ្ឋ ស្ថាប័នក្រៅរដ្ឋាភិបាល និងស្ថាប័នឯកជនក្នុងវិស័យកសិកម្ម អភិវឌ្ឍន៍ជនបទ បរិស្ថាន ធនធានទឹក និងពាណិជ្ជកម្មជាដើម។

Best regards
Sovanara
